name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TEST_AUTH_TOKEN: ${{ secrets.ALPHA_TEST_AUTH_TOKEN }}
      TEST_CACHE_NAME: python-integration-test-cache

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel build
          pip install -e . --extra-index-url https://momento.jfrog.io/artifactory/api/pypi/pypi-public/simple

      - name: Build package
        run: python -m pip install -e .

      - name: Run tests
        run: python -m unittest discover -v
