name: CI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TEST_AUTH_TOKEN: ${{ secrets.ALPHA_TEST_AUTH_TOKEN }}
      TEST_CACHE_NAME: python-integration-test-cache

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: "gabrielfalcao/pyenv-action@v5"
        with:
          versions: 3.8.12, 3.9.10

      - name: Build package and run tests
        run: |
          pyenv local 3.8.12 3.9.10
          tox
